# App config
server.port=${SERVER_PORT:8081}
spring.application.name=coffee-order-service
server.servlet.contextPath=/coffee-order-service

## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

##JPA and hibernate
spring.jpa.show-sql=true
hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

### Postgres datasource prod
spring.datasource.url=jdbc:postgresql://localhost:5432/coffee-app
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.liquibase.change-log= classpath:db/changelog/db.changelog-master.xml
spring.security.user.name= admin
spring.security.user.password= admin
